New 8 model language and new 9 model category Voitovych
IT-Academy-Social-Projects-KRV/CodeArena-Django pull request #17
Opened 2021-08-14 00:00 UTC by alexandrv1111

created language and category models

2021-08-14 15:23 UTC, MetalMari approved these changes

2021-08-15 08:48 UTC, okslisovska commented
Here I can see the following issues:
1.As we can see from migrations/0001_initial.py, the category id will be BigAutoField instead of ObjectIdField (the same for the language). The application throws an error about it (don't remember at which point exactly). So to avoid this we need to add _id=...ObjectId... to the category model. Or (not 100% sure, but just noticed it)  maybe in  category/apps.py class CategoryConfig set somehow the default_auto_field to ObjectId?
2.Since we have 'ENFORCE_SCHEMA': False in settings.py DATABASES, I believe that we have no need to run migrations with MongoDB.

2021-08-15 09:14 UTC, okslisovska commented
And if we are going to use Django's admin, we need our models to be registered at admin.py. But unfortunately, the admin still does not want to behave when I am testing( So I quit trying and quickly created a view function for testing. Anyway we are going to create our own admin for the site.

2021-08-15 16:56 UTC, dmytrosmetanin approved these changes
Approved

2021-08-16 08:29 UTC, vvelizariy commented on .gitignore
> +v
what is `v` stands for?

2021-08-16 08:29 UTC, vvelizariy commented on codeArena/category/migrations/0001_initial.py
> +# Generated by Django 3.2.6 on 2021-08-13 23:31
Can be omitted. Useless information.

2021-08-16 08:41 UTC, MrSancho42 requested changes

2021-08-16 08:41 UTC, MrSancho42 commented on .gitignore
> +v
Is this mistake?

2021-08-16 08:41 UTC, MrSancho42 commented on codeArena/language/models.py
> +    title = models.CharField(max_length=100)
We named this field "name" in SQL Designer

2021-08-16 08:41 UTC, MrSancho42 commented on codeArena/category/models.py
> +    title = models.CharField(max_length=100)
We named this field "name" in SQL Designer

2021-08-16 08:41 UTC, MrSancho42 commented on codeArena/language/models.py
> +        return self.title
In end of file recommended to leave a empty line

2021-08-16 10:17 UTC, MrSancho42 approved these changes

2021-08-16 10:57 UTC, MrSancho42 requested changes

2021-08-16 10:57 UTC, MrSancho42 commented on codeArena/category/models.py
> +
This strings need to be removed

2021-08-16 10:57 UTC, MrSancho42 commented on codeArena/category/models.py
> +# from django.db import models as m
This string need to be removed

2021-08-16 10:57 UTC, MrSancho42 commented on codeArena/language/models.py
> +# Create your models here.
Comments need to be removed

2021-08-17 08:49 UTC, closed without merging