Fix 7 e 5 create table vacancies coder vacancies viktoriia zakharko
IT-Academy-Social-Projects-KRV/CodeArena-Django pull request #31
Opened 2021-09-01 17:42 UTC by Viktorika-p

2021-09-01 20:29 UTC, okslisovska commented
This pull request can not be approved by me due to the following issues:
1. The changes in settings.py are very suspicious. 
2. There are some issues with imports.
3. There is no need for the coder_vacancies table. Django has ManyToManyField() for it. We have it on our DB schema just to represent many-to-many relationship.

2021-09-02 06:53 UTC, s0fko requested changes

2021-09-02 06:53 UTC, s0fko commented on codeArena/codeArena/settings.py
> +SECRET_KEY = 'erofeorpegiheigeporg'
This changes shouldn't be committed.

For using and understanding local variables please have a look at [Decouple](https://pypi.org/project/python-decouple/) library and create .env file with them. We imported this library at 11 string and `config()` is it's method, which imports variables from .env file

Please change this thing everywhere, where `config()` method is using

2021-09-02 06:53 UTC, s0fko commented on codeArena/codeArena/settings.py
> -    'competition',
'competition' app was created by me and you shouldn't delete it from here

If you haven't this changes in your local repository, than please pull changes from GitHub

2021-09-02 06:53 UTC, s0fko commented on codeArena/codeArena/settings.py
> +
Please remove empty string, according to [pep8](https://www.python.org/dev/peps/pep-0008/)

2021-09-02 06:53 UTC, s0fko commented on codeArena/codeArena/settings.py
> +                    'routers.db_routers.MongoRouter']
Please add newline to the end of file

2021-09-02 06:53 UTC, s0fko commented on codeArena/vacancies/models.py
> +    company = models.CharField(max_length=20)
I guess we need more than 20 characters for company names

2021-09-02 06:53 UTC, s0fko commented on codeArena/vacancies/models.py
> +
Please add only 2 blank lines between the import statements and other code

2021-09-02 06:53 UTC, s0fko commented on codeArena/vacancies/models.py
> +
Please add only 2 blank lines between the classes

2021-09-02 06:53 UTC, s0fko commented on codeArena/vacancies/models.py
> +class Coder_vacancies(models.Model):
Please use the CapWords convention for class names according to [pep8](https://www.python.org/dev/peps/pep-0008/#class-names)

So, your class name should be named `CoderVacancies` instead

2021-09-02 12:42 UTC, closed without merging