Created serializers for User and Coder tables
IT-Academy-Social-Projects-KRV/CodeArena-Django pull request #34
Opened 2021-09-01 21:58 UTC by dmytrosmetanin

Pls check my changes, comment if anything and approve if everything's fine.

2021-09-02 06:18 UTC, MrSancho42 requested changes
Are .create(), and .update() UserSerializer's methods?

2021-09-02 06:18 UTC, MrSancho42 commented on codeArena/user/serializers.py
> +class UserSerializer(serializers.ModelSerializer):
Vitaliy recommended use serializer.Serializer for complex tables, couse it more flexible

2021-09-02 06:18 UTC, MrSancho42 commented on codeArena/user/serializers.py
> +class CoderSerializer(serializers.ModelSerializer):
In this case same issue as higher

2021-09-02 06:18 UTC, MrSancho42 commented on codeArena/user/serializers.py
> +    if "password" in validated_data:
PEP8 recommend use single quotes

2021-09-02 08:05 UTC, vvelizariy commented on codeArena/user/serializers.py
> +class UserSerializer(serializers.ModelSerializer):
For user it can be used. As we will not manipulate on user fields.

2021-09-02 15:30 UTC, vvelizariy commented on codeArena/user/serializers.py
> +        from django.contrib.auth.hashers import make_password
As this import is used more than once, move it to global imports on top

2021-09-06 09:11 UTC, MetalMari approved these changes

2021-09-06 10:31 UTC, s0fko approved these changes

2021-09-06 11:11 UTC, Viktorika-p approved these changes

2021-09-06 12:24 UTC, MrSancho42 approved these changes

2021-09-06 12:24 UTC, merged